cadastros/urls.py
from django.contrib import admin
from django.urls import path
from .views import ImprimirPmoc,RespTecnicoList,importar_atividades,ImprimirCronograma,ImprimirEquipamento,RespTecnicoCreate,RespTecnicoUpdate,EmpresaUpdate,EmpresaList,importar_atendimentos,importar_equipamentos,ClienteList,ClienteDelete,ClienteCreate,ClienteUpdate,EquipamentoList,ContratoList,AtendimentoList,ContratoDelete,ContratoCreate,ContratoUpdate,AtendimentoCreate,AtendimentoDelete,AtendimentoUpdate,EquipamentoCreate,EquipamentoUpdate,EquipamentoDelete,AtividadeList,AtividadeCreate,AtividadeDelete,AtividadeUpdate,TipoList,TipoCreate,TipoUpdate,TipoDelete


urlpatterns = [

    path('sistema/imprimir_pmoc/<uuid:id>/', ImprimirPmoc, name='imprimir'),
    path('sistema/imprimir_cronograma/<uuid:id>/', ImprimirCronograma, name='imprimir_cronograma'),
    path('sistema/imprimir_equipamento/<uuid:id>/', ImprimirEquipamento, name='imprimir_equipamento'),

    path('sistema/empresas/', EmpresaList, name='empresa_list'),
    path('sistema/empresas/editar/<uuid:id>/', EmpresaUpdate, name='empresa_edit'),

    path('sistema/resp_tecnico/', RespTecnicoList, name='resp_tecnico_list'),
    path('sistema/resp_tecnico/cadastrar/', RespTecnicoCreate, name='resp_tecnico_create'),
    path('sistema/resp_tecnico/editar/<uuid:id>/', RespTecnicoUpdate, name='resp_tecnico_edit'),

    path('sistema/clientes/', ClienteList, name='cliente_list'),
    path('sistema/clientes/cadastrar/', ClienteCreate, name='cliente_create'),
    path('sistema/clientes/editar/<uuid:id>/', ClienteUpdate, name='cliente_edit'),
    path('sistema/clientes/excluir/<uuid:id>/', ClienteDelete, name='cliente_delete'),

    path('sistema/equipamentos/<uuid:id>/', EquipamentoList, name='equipamento_list'),
    path('sistema/equipamentos/cadastrar/<uuid:id>', EquipamentoCreate, name='equipamento_create'),
    path('sistema/equipamentos/editar/<uuid:id>/', EquipamentoUpdate, name='equipamento_edit'),
    path('sistema/equipamentos/excluir/<uuid:id>/', EquipamentoDelete, name='equipamento_delete'),

    path('sistema/contratos/', ContratoList, name='contrato_list'),
    path('sistema/contratos/cadastrar/', ContratoCreate, name='contrato_create'),
    path('sistema/contratos/editar/<uuid:id>/', ContratoUpdate, name='contrato_edit'),
    path('sistema/contratos/excluir/<uuid:id>/', ContratoDelete, name='contrato_delete'),

    path('sistema/tipos/', TipoList, name='tipo_list'),
    path('sistema/tipos/cadastrar/', TipoCreate, name='tipo_create'),
    path('sistema/tipos/editar/<uuid:id>/', TipoUpdate, name='tipo_edit'),
    path('sistema/tipos/excluir/<uuid:id>/', TipoDelete, name='tipo_delete'),

    path('sistema/atendimentos/<uuid:contrato_id>/', AtendimentoList, name='atendimento_list'),
    path('sistema/atendimentos/cadastrar/<uuid:contrato_id>/', AtendimentoCreate, name='atendimento_create'),
    path('sistema/atendimentos/editar/<uuid:id>/', AtendimentoUpdate, name='atendimento_edit'),
    path('sistema/atendimentos/excluir/<uuid:id>/', AtendimentoDelete, name='atendimento_delete'),

    path('sistema/atividades/<uuid:id>/', AtividadeList, name='periodicidade_list'),
    path('sistema/atividades/cadastrar/<uuid:id>/', AtividadeCreate, name='periodicidade_create'),
    path('sistema/atividades/excluir/<uuid:id>/', AtividadeDelete, name='periodicidade_delete'),
    path('sistema/atividades/editar/<uuid:id>/', AtividadeUpdate, name='periodicidade_edit'),

    path('sistema/import/atendimentos', importar_atendimentos, name='importar_atendimentos'),
    path('sistema/import/equipamentos', importar_equipamentos, name='importar_equipamentos'),
    path('sistema/import/atividades', importar_atividades, name='importar_atividades'),

]

core/urls.py
from django.contrib import admin
from django.urls import path
from .views import Dashboard

urlpatterns = [
    path('dashboard/', Dashboard.as_view(), name='dashboard'), 
]

plusplan/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('usuarios.urls')),
    path('', include('core.urls')),
    path('', include('cadastros.urls')),
    path('', include('financeiros.urls')),
    path('', include('planejamentos.urls')),
]

cadastros/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid
from django.conf import settings


class Responsavel_Tecnico(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    TIPO_DOCUMENTO_CHOICES = [
        ('pf', 'Pessoal Física'),
        ('pj', 'Pessoa Jurídica'),
    ]

    tipo_documento = models.CharField(max_length=4, choices=TIPO_DOCUMENTO_CHOICES)
    cnpj = models.CharField(max_length=18, unique=True, null=True, blank=True)
    cpf = models.CharField(max_length=14, unique=True, null=True, blank=True)

    nome = models.CharField(verbose_name="Nome", max_length=45, null=True)   
    endereco = models.CharField(verbose_name="Endereço", max_length=255, blank=True)
    bairro = models.CharField(verbose_name="Bairro", max_length=45, blank=True)
    cidade = models.CharField(verbose_name="Cidade", max_length=45, blank=True)
    uf = models.CharField(verbose_name="UF", max_length=2, blank=True)
    cep = models.CharField(verbose_name="Cep", max_length=45, blank=True) 
    telefone = models.CharField(verbose_name="Telefone", max_length=45, blank=True) 
    email = models.EmailField(verbose_name="Email", max_length=45, blank=True) 
    
    rigistro_conselho = models.CharField(verbose_name="Registro no Conselho de Classe", max_length=45, blank=True, null=True)
    art = models.CharField(verbose_name="ART", max_length=45, blank=True, null=True)    
    
    empresa = models.OneToOneField('Empresa', on_delete=models.SET_NULL, null=True, blank=True, related_name='Responsavel_Tecnico')
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    registro_atualizado = models.DateTimeField(auto_now=True)
    registro_criado = models.DateTimeField(auto_now_add=True)

    def __str__(self): 
        return self.nome

    class Meta:
        db_table = 'resp_tecnico'


class Empresa(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    TIPO_DOCUMENTO_CHOICES = [
        ('pf', 'Pessoal Física'),
        ('pj', 'Pessoa Jurídica'),
    ]

    tipo_documento = models.CharField(max_length=4, choices=TIPO_DOCUMENTO_CHOICES)
    cnpj = models.CharField(max_length=18, unique=True, null=True, blank=True)
    cpf = models.CharField(max_length=14, unique=True, null=True, blank=True)

    nome = models.CharField(verbose_name="Nome", max_length=255, null=True)   
    endereco = models.CharField(verbose_name="Endereço", max_length=255, blank=True)
    bairro = models.CharField(verbose_name="Bairro", max_length=45, blank=True)
    cidade = models.CharField(verbose_name="Cidade", max_length=45, blank=True)
    uf = models.CharField(verbose_name="UF", max_length=2, blank=True)
    cep = models.CharField(verbose_name="Cep", max_length=45, blank=True) 
    telefone = models.CharField(verbose_name="Telefone", max_length=45, blank=True) 
    email = models.EmailField(verbose_name="Email", max_length=45, blank=True) 
    
    resp_tecnico = models.OneToOneField('Responsavel_Tecnico', on_delete=models.SET_NULL, blank=True, null=True, related_name='empresa_do_responsavel')
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,related_name='empresa_do_usuario')
    registro_atualizado = models.DateTimeField(auto_now=True)
    registro_criado = models.DateTimeField(auto_now_add=True)

    def __str__(self): 
        return self.nome

    class Meta:
        db_table = 'empresa'


class Cliente(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    TIPO_DOCUMENTO_CHOICES = [
        ('pf', 'Pessoal Física'),
        ('pj', 'Pessoa Jurídica'),
    ]

    tipo_documento = models.CharField(max_length=4, choices=TIPO_DOCUMENTO_CHOICES)
    cnpj = models.CharField(max_length=18, unique=True, null=True, blank=True)
    cpf = models.CharField(max_length=14, unique=True, null=True, blank=True)

    nome = models.CharField(verbose_name="Nome", max_length=45, null=True)   
    endereco = models.CharField(verbose_name="Endereço", max_length=255, blank=True)
    bairro = models.CharField(verbose_name="Bairro", max_length=45, blank=True)
    cidade = models.CharField(verbose_name="Cidade", max_length=45, blank=True)
    uf = models.CharField(verbose_name="UF", max_length=2, blank=True)
    cep = models.CharField(verbose_name="Cep", max_length=45, blank=True) 
    telefone = models.CharField(verbose_name="Telefone", max_length=45, blank=True) 
    email = models.EmailField(verbose_name="Email", max_length=45, blank=True) 
    
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    empresa = models.ForeignKey(Empresa, on_delete=models.CASCADE,blank=True, null=True)
    registro_atualizado = models.DateTimeField(auto_now=True)
    registro_criado = models.DateTimeField(auto_now_add=True)

    def __str__(self): 
        return self.nome

    class Meta:
        db_table = 'cliente'


class Contrato(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    pregao = models.CharField(verbose_name="Pregão", max_length=45, null=True)   
    contrato = models.CharField(verbose_name="Contrato", max_length=45, null=True)   
    objeto = models.TextField(verbose_name="Objeto do Contrato", blank=True)

    custo = models.DecimalField(default=0,max_digits=10, decimal_places=2, verbose_name="Valor Contratual (Global)")  
    expectativa_faturamento = models.DecimalField(default=0,max_digits=10, decimal_places=2,verbose_name="Expectativa de faturamento mensal (Conforme Aditivos)")
    qtd_equipamento_ativo = models.DecimalField(default=0,max_digits=10, decimal_places=0,verbose_name="Equipamentos Ativos", blank=True)
    qtd_equipamento_inativo = models.DecimalField(default=0,max_digits=10, decimal_places=0,verbose_name="Equipamentos Inativos", blank=True)
    equipe_fixa = models.CharField(verbose_name="Equipe fixa",max_length=45, choices=[('Sim', 'Sim'), ('Não', 'Não')],blank=True, null=True)   
    qtd_equipe = models.DecimalField(default=0,max_digits=10, decimal_places=0,verbose_name="Quantidade de equipe", blank=True)
    veiculo = models.DecimalField(default=0,max_digits=10, decimal_places=0,verbose_name="Quantidade de veículos", blank=True)
    pagt_pecas = models.CharField(verbose_name="Quem paga as peças", max_length=45, blank=True, null=True)  
    pagt_corretivas = models.CharField(verbose_name="Quem paga as corretivas", max_length=45, blank=True, null=True)  
    pagt_mensal_demanda = models.CharField(verbose_name="Pagamento é mensal ou por demanda",max_length=45, choices=[('Mensal', 'Mensal'), ('Demanda', 'Demanda')],blank=True, null=True)   
    periodicidade =  models.CharField(verbose_name="Periodicidade das preventivas - (MENSAL/BIMESTRAL/SEMESTRAL/ANUAL)", max_length=45, blank=True,null=True)  
    inicio_contrato =  models.DateField(verbose_name="Inicio do contrato", blank=True,null=True)  
    periodo_renovacao = models.CharField(verbose_name="Periodo de renovação - EX.: 01 (UM) ANO OU 02 (DOIS) ANOS e 12 (DOZE) DIAS)", max_length=45, blank=True,null=True)  
    fim_contrato =  models.DateField(verbose_name="Fim do contrato", blank=True,null=True)   
    data_renovacao = models.DateField(verbose_name="Data de renovação", blank=True,null=True)  
    vigencia_final = models.CharField(verbose_name="Vigência final", max_length=45, blank=True,null=True)  
    prazo_corretiva = models.TextField(verbose_name="Prazo de corretivas", blank=True)
    link_doc = models.CharField(verbose_name="Link dos documentos", max_length=255, blank=True, null=True)     
    
    empresa = models.ForeignKey(Empresa, on_delete=models.CASCADE)
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    registro_atualizado = models.DateTimeField(auto_now=True)
    registro_criado = models.DateTimeField(auto_now_add=True)

    def __str__(self): 
        return self.contrato

    class Meta:
        db_table = 'contrato'


class Atendimento(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    codigo = models.CharField(max_length=45, blank=True, null=True, verbose_name='Código')
    cnpj = models.CharField(max_length=25, null=True, blank=True)
    nome = models.CharField(verbose_name="Nome", max_length=45, null=True)   
    endereco = models.CharField(verbose_name="Endereço", max_length=255, blank=True)
    bairro = models.CharField(verbose_name="Bairro", max_length=45, blank=True)
    cidade = models.CharField(verbose_name="Cidade", max_length=45, blank=True)
    uf = models.CharField(verbose_name="UF", max_length=2, blank=True)
    cep = models.CharField(verbose_name="Cep", max_length=9, blank=True) 
    telefone = models.CharField(verbose_name="Telefone", max_length=45, blank=True) 
    email = models.EmailField(verbose_name="Email", max_length=45, blank=True) 
    
    contrato = models.ForeignKey(Contrato, on_delete=models.CASCADE)
    empresa = models.ForeignKey(Empresa, on_delete=models.CASCADE,blank=True, null=True)
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    registro_atualizado = models.DateTimeField(auto_now=True)
    registro_criado = models.DateTimeField(auto_now_add=True)

    def __str__(self): 
        return self.nome

    class Meta:
        db_table = 'atendimento'


class Tipo(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    nome = models.CharField(max_length=45, verbose_name='Nome') 
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    registro_atualizado = models.DateTimeField(auto_now=True)
    registro_criado = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.nome
    
    class Meta:
        db_table = 'tipo'

class Equipamento(models.Model):

financeiros/models.py
from django.db import models
from django.contrib.auth.models import User
from cadastros.models import Contrato # Certifique-se de importar corretamente
import uuid
from django.conf import settings


class Financeiro(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    competencia = models.CharField(verbose_name="Competencia", max_length=45, null=True)  
    preventiva = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Preventiva", null=True, blank=True)
    corretiva = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Corretiva", null=True, blank=True)
    instalacao = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Instalação", null=True, blank=True)
    pecas = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Peças", null=True, blank=True)
    custo = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Custo")
    contrato = models.ForeignKey(Contrato, on_delete=models.CASCADE)
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    registro_atualizado = models.DateTimeField(auto_now=True)
    registro_criado = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.competencia}' 

    class Meta:
        db_table = 'financeiro'

cadastros/templates/cadastros/exclusao_cliente.html
{% extends 'base.html' %}

{% block content %}

{% load static %}

{% load crispy_forms_tags %}

<!DOCTYPE html>
<html>
<head>
    <title>Confirmação de Exclusão</title>
</head>
<body>   
    <div class="card card-danger">
        <div class="card-header">
          <h3 class="card-title">Você deseja realmente excluir?</h3>
        </div>
      
        <form method="post">
            {% csrf_token %}
          <div class="card-body">
            <div class="form-group">
                <input type="submit" value="Sim" class="btn btn-danger">
                <a href="{{ url_cancelar }}">Cancelar</a>
              <!--<input type="email" class="form-control" id="exampleInputEmail1" placeholder="Enter email">-->
            </div>
            {% if messages %}
              <div class="alert alert-warning">
                  {% for m in messages %}
                      <p {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ m }}</p>
                  {% endfor %}
              </div>
            {% endif %}
            
        </form>
      </div>
</body>
</html>

{% endblock %}

cadastros/templates/cadastros/importar.html
<!-- importar.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Importar Dados</title>
</head>
<body>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="file" name="arquivo_excel">
        <button type="submit">Importar</button>
    </form>
</body>
</html>

cadastros/templates/cadastros/listar_periodicidades.html
{% extends 'base.html' %}

{% block content %}

{% load static %}

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0">Atividades</h1>
                    </div><!-- /.col -->
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item">
                                <a href="{% url 'dashboard' %}">Home</a> /
                                <a href="{% url 'contrato_list' %}">Contratos</a> /
                                <a href="#" onclick="history.go(-1)">Atendimentos</a> /
                                Equipamentos
                            </li>
                            
                            
                            <li class="breadcrumb-item active">Atividades</li>
                        </ol>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
          </div>

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- DataTales Example -->
                    <div class="card shadow mb-4">
                        <div class="card-header py-4" style="background-color: blue; position: relative;">
                            <h6 class="m-0 font-weight-bold text-white" style="position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%); font-size: 20px;">ATIVIDADES DO PMOC</h6>
                        </div>
                        <br>
                        {% if messages %}
                            <div class="alert alert-warning">
                                {% for m in messages %}
                                    <p {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ m }}</p>
                                {% endfor %}
                            </div>
                        {% endif %}

                        <div class="card-body">
                            

                            {% for equipamento in equipamentos %}
                                <div class="row justify-content-between">
                                    <div class="col">
                                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modal-lg-{{ equipamento.id }}">
                                            + Atividade
                                        </button>
                                    </div>
                                </div>
                            
                            
                                <!-- Modal -->
                                <div class="modal fade" id="modal-lg-{{ equipamento.id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                    <div class="modal-dialog modal-lg" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header" style="background-color: blue; color: white;">
                                                <h5 class="modal-title" id="exampleModalLabel">Adicionar Atividade</h5>
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                            
                                            <div class="modal-body">
                                                {% load crispy_forms_tags %}
                                                <form method="POST" action="{% url 'periodicidade_create' equipamento.id %}" class="lead px-4" enctype="multipart/form-data">
                                                    {% csrf_token %}
                                                    <div class="row">
                                                        <div class="col-12">
                                                            {{ form|crispy }}
                                                        </div>
                                                    </div>
                                                    <p class="lead px-0">
                                                        <button type="submit" class="btn btn-primary">Salvar</button>
                                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                                                    </p>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}

                    
                            <div class="table-responsive">
                                <table class="table table-bordered table-sm" id="data" width="100%" cellspacing="0">
                                    <thead>
                                        <tr style="background-color:rgba(0, 0, 0, 0.726); color: white;">
                                            <th>Contrato</th>
                                            <th>Equipamento</th>
                                            <th>Tag</th>
                                            <th>Mês</th>
                                            <th>Periodicidade</th>
                                            <th>Ação</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for periodicidade in periodicidades %}
                                        <tr>
                                            <td><a href="{% url 'periodicidade_edit' periodicidade.id %}">{{ periodicidade.equipamento.atendimento.contrato }}</td>
                                            <td>{{ periodicidade.equipamento.tipo }}</a></td>
                                            <td>{{ periodicidade.equipamento.tag }}</td>
                                            <td>{{ periodicidade.get_competencia_display  }}</td>
                                            <td>{{ periodicidade.periodicidade }}</td>
                                            <td>
                                                <a href="{% url 'periodicidade_delete' periodicidade.id %}" title="Excluir">
                                                    <i class="fa fa-trash icon-red" aria-hidden="true"></i>
                                                </a>
                                            </td>
                                            
                                        </tr>
                                        {% empty %}
                                        <tr>
                                            <td colspan="5">Nenhum equipamento registrado </td>
                                        </tr>
                                        {% endfor %}

                                    </tbody>
                                </table>

                               <!-- <nav aria-label="Navegação de página">
                                  <ul class="pagination justify-content-center">
                                      {% if page_obj.has_previous %}
                                        <li class="page-item">
                                          <a class="page-link" href="?page={{page_obj.previous_page_number}}" tabindex="-1">&laquo;Anterior</a>
                                        </li>
                                      {% endif %}

                                        <li class="page-item active">
                                          <a class="page-link" href="#">Página: {{ page_obj.number }} de {{ page_obj.paginator.num_pages }} <span class="sr-only">(atual)</span></a>
                                        </li>

                                      {% if page_obj.has_next %}
                                        <li class="page-item">
                                          <a class="page-link" href="?page={{page_obj.next_page_number}}">&raquo;Próximo</a>
                                        </li>
                                      {% endif %}
                                  </ul>
                                </nav> -->

                            </div>
                        </div>
                    </div>

                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

</body>

{% endblock %}

cadastros/templates/cadastros/pmoc_equipamentos.html
{% block content %}

{% load static %}

<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ANEXO I</title>

    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 30px;
            font-size: 12pt;
        }
        h3 {
            text-align: left;
            font-weight: bold;
        }
        p, blockquote {
            text-align: justify;
            margin-bottom: 20px;
        }
        .header-img {
            display: flex;
            align-items: center;
            justify-content: space-between;
            border: 1px solid #000; /* Adiciona uma borda para visualização */
            padding: 10px; /* Adiciona espaçamento interno */
        }
        .header-img img {
            max-width: 100px; /* Define a largura máxima para a imagem */
            height: auto; /* Garante que a altura seja ajustada automaticamente */
        }
        .header-img p {
            margin: 0; /* Remove as margens padrão do parágrafo */
            text-align: center; /* Centraliza o texto */
        }
        .approval-info {
            font-weight: bold; /* Deixa o texto em negrito */
        }
        .negrito {
            font-weight: bold;
        }
        .page-break {
            page-break-before: always;
        }
    </style>
</head>
<body>
    <header class="header-img">
        <img src="{% static 'img/logo_imqpa.jpg' %}">
        <p>Plano de Manutenção, Operação e Controle</p>
        <p class="approval-info">Aprovação: <br> {{ atendimento.contrato.inicio_contrato|date:"d/m/Y" }} <br> Revisão: 00</p>
    </header>

    <h2 style="text-align: center;">ANEXO I</h2>
    <h2 style="text-align: center;">CADASTRO DE EQUIPAMENTOS / INSTALAÇÕES</h2>

    <table border="1" style="border-collapse: collapse;">
        <tbody>
            <tr>
                <td>Empresa</td>
                <td>IMQPA - INSTITUTO MINEIRO DE QUALIFICAÇÃO PROFISSIONAL E ASSESSORIA</td>
            </tr>
            <tr>
                <td>Contrato Nº</td>
                <td>2022.7421.4642</td>
            </tr>
            <tr>
                <td>Data</td>
                <td>14/09/2022</td>
            </tr>
        </tbody>
    </table>

    <br>

    <table border="1" style="border-collapse: collapse;">
        <thead>
            <tr>
                <th>PREFIXO</th>
                <th>DEPENDÊNCIA</th>
                <th>Nº DO BEM</th>
                <th>MARCA DO EQUIPAMENTO</th>
                <th>TIPO</th>
                
                <th>MOD. EVAPORADOR</th>
                <th>MOD. CONDENSADOR</th>
                <th>AMBIENTE</th>
                <th>CAPACIDADE (TR)</th>
                <th>GÁS REFRIGERANTE</th>
            </tr>
        </thead>
        <tbody>
            {% for equipamento in equipamentos %}

            <tr>
                <td>{{ equipamento.codigo }}</td>
                
                <td>{{ equipamento.atendimento }}</td>
                <td></td>
                <td>{{ equipamento.marca }}</td>
                <td>{{ equipamento.tipo }}</td>
                
                <td>{{ equipamento.mod_evaporador }}</td>
                <td>{{ equipamento.mod_condensador }}</td>
                <td>{{ equipamento.ambiente }}</td>
                <td>{{ equipamento.capacidade }}</td>
                <td>{{ equipamento.gas_refrigerante }}</td>
            </tr>

            {% endfor %}
        </tbody>
    </table>
</body>
</html>


{% endblock %}